#!/bin/sh

if [ ! -f /usr/bin/xwalk ]; then
   echo "The xwalk binary could not be found. Exiting."
   exit 1
fi

exec /usr/bin/xwalk --allow-external-extensions-for-remote-sources --fullscreen --external-extensions-path=/usr/lib/tizen-extensions-crosswalk "$@"
