#!/bin/bash
# Copyright (c) 2013 Intel Corporation. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if [ ! `which cpplint.py` ]; then
   echo -e "\nPlease make sure cpplint.py is in your PATH. It is part of depot_tools inside Chromium repository."
   exit 1
fi

# Store current dir and change to repository root dir.
OLD_PWD=$PWD
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SELF_DIR/..

# FIXME(cmarcelo): the exception 'runtime/references' is for system_info/, we
# need to verify whether is really necessary or should be fixed.
FILTERS="-readability/streams,-runtime/references"

# TODO(cmarcelo): Skipping directories so we can enable style
# gradually, since it wasn't enforced before.
cpplint.py --filter="$FILTERS" $(find \
                               ! -path './out*' ! -path './.git*' \
                               ! -path './demos' ! -path './examples' \
                               ! -path './packaging' \
                               ! -name 'XW_Extension.h' \
                               ! -name 'XW_Extension_SyncMessage.h' \
                               ! -name 'picojson.*' \
                               ! -path './download/*' \
                               \( -name '*.h' -o -name '*.cc' \) )

# Return to previous dir and return the code returned by cpplint.py
RET_VAL=$?
cd $OLD_PWD
exit $RET_VAL
